#ifndef FSDATA_H
#define FSDATA_H
static const char index_html_markup[] = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Wi-Fi Setup</title>\n"
"    <style>\n"
"        body {\n"
"            font-family: Arial, sans-serif;\n"
"            margin: 20px;\n"
"        }\n"
"\n"
"        h1 {\n"
"            font-size: 24px;\n"
"            margin-bottom: 20px;\n"
"        }\n"
"\n"
"        .wifi-list-container {\n"
"            max-height: 300px;\n"
"            /* Set maximum height for scrollability */\n"
"            overflow-y: auto;\n"
"            border: 1px solid #ccc;\n"
"            padding: 10px;\n"
"            border-radius: 5px;\n"
"        }\n"
"\n"
"        .wifi-item {\n"
"            display: flex;\n"
"            align-items: center;\n"
"            justify-content: space-between;\n"
"            padding: 10px;\n"
"            border-bottom: 1px solid #ddd;\n"
"            cursor: pointer;\n"
"            transition: background-color 0.2s;\n"
"        }\n"
"\n"
"        .wifi-item:hover {\n"
"            background-color: #f5f5f5;\n"
"        }\n"
"\n"
"        .wifi-item:last-child {\n"
"            border-bottom: none;\n"
"        }\n"
"\n"
"        .wifi-info {\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"        }\n"
"\n"
"        .wifi-name {\n"
"            font-weight: bold;\n"
"        }\n"
"\n"
"        .wifi-auth {\n"
"            font-size: 0.9em;\n"
"            color: #777;\n"
"        }\n"
"\n"
"        .wifi-signal {\n"
"            font-size: 1.2em;\n"
"        }\n"
"\n"
"        .password-input {\n"
"            margin-top: 20px;\n"
"            display: none;\n"
"            /* Initially hidden */\n"
"        }\n"
"\n"
"        .password-input label {\n"
"            font-weight: bold;\n"
"        }\n"
"\n"
"        .password-input input {\n"
"            width: calc(100% - 20px);\n"
"            padding: 5px;\n"
"            margin-top: 5px;\n"
"            margin-bottom: 10px;\n"
"            border: 1px solid #ccc;\n"
"            border-radius: 3px;\n"
"        }\n"
"\n"
"        .password-input button {\n"
"            padding: 10px 20px;\n"
"            background-color: #007BFF;\n"
"            color: white;\n"
"            border: none;\n"
"            border-radius: 3px;\n"
"            cursor: pointer;\n"
"            font-size: 16px;\n"
"        }\n"
"\n"
"        .password-input button:hover {\n"
"            background-color: #0056b3;\n"
"        }\n"
"\n"
"        #status {\n"
"            margin-top: 20px;\n"
"            color: #555;\n"
"        }\n"
"    </style>\n"
"</head>\n"
"\n"
"<body>\n"
"    <h1>Wi-Fi Setup</h1>\n"
"    <div class=\"wifi-list-container\" id=\"wifiList\"></div>\n"
"    <div id=\"passwordInput\" class=\"password-input\">\n"
"        <label for=\"password\">Password:</label>\n"
"        <input type=\"password\" id=\"password\" name=\"password\" required><br>\n"
"        <button onclick=\"submitCredentials(event)\">Connect</button>\n"
"    </div>\n"
"    <p id=\"selectedNetwork\"></p>\n"
"    <p id=\"status\"></p>\n"
"    <script>\n"
"        let selectedNetwork = null\n"
"\n"
"        document.addEventListener(\"DOMContentLoaded\", function () {\n"
"            loadWifiList()\n"
"        })\n"
"\n"
"        async function loadWifiList() {\n"
"            document.getElementById('status').innerText = \"Scanning for Wi-Fi networks...\"\n"
"            const response = await fetch('/scan.json')\n"
"            if (response.ok) {\n"
"                const wifiList = await response.json()\n"
"                const listContainer = document.getElementById('wifiList')\n"
"                listContainer.innerHTML = \"\" // Clear existing list\n"
"\n"
"                wifiList.forEach(network => {\n"
"                    const item = document.createElement('div')\n"
"                    item.className = 'wifi-item'\n"
"                    item.onclick = () => selectNetwork(network)\n"
"\n"
"                    const info = document.createElement('div')\n"
"                    info.className = 'wifi-info'\n"
"                    info.innerHTML = `\n"
"                            <div class=\"wifi-name\">${network.ssid}</div>\n"
"                            <div class=\"wifi-auth\">${getAuthModeText(network.auth_mode)}</div>\n"
"                        `\n"
"\n"
"                    const signal = document.createElement('div')\n"
"                    signal.className = 'wifi-signal'\n"
"                    signal.innerHTML = getSignalStrengthIcon(network.rssi)\n"
"\n"
"                    item.appendChild(info)\n"
"                    item.appendChild(signal)\n"
"                    listContainer.appendChild(item)\n"
"                })\n"
"\n"
"                document.getElementById('status').innerText = \"Select a Wi-Fi network from the list.\"\n"
"            } else {\n"
"                document.getElementById('status').innerText = \"Failed to scan for Wi-Fi networks.\"\n"
"            }\n"
"        }\n"
"\n"
"        function getAuthModeText(authMode) {\n"
"            const modes = {\n"
"                0: \"Open\",\n"
"                1: \"WEP\",\n"
"                2: \"WPA\",\n"
"                3: \"WPA2\",\n"
"                4: \"WPA/WPA2 Mixed\",\n"
"                5: \"WPA2-Enterprise\"\n"
"            }\n"
"            return modes[authMode] || \"Unknown\"\n"
"        }\n"
"\n"
"        function getSignalStrengthIcon(rssi) {\n"
"            if (rssi >= -50) return \"🔵\" // Strong\n"
"            if (rssi >= -70) return \"🟢\" // Moderate\n"
"            return \"⚫\" // Weak\n"
"        }\n"
"\n"
"        function selectNetwork(network) {\n"
"            selectedNetwork = network\n"
"            document.getElementById('selectedNetwork').innerText = `Selected: ${network.ssid}`\n"
"            document.getElementById('passwordInput').style.display = \"block\"\n"
"        }\n"
"\n"
"        async function submitCredentials(event) {\n"
"            event.preventDefault()\n"
"            if (!selectedNetwork) {\n"
"                document.getElementById('status').innerText = \"Please select a network.\"\n"
"                return\n"
"            }\n"
"            const password = document.getElementById('password').value\n"
"\n"
"            document.getElementById('status').innerText = \"Testing Wi-Fi credentials, the led on you device should start flashing, if it turns solid you have successfully connected and you can close this page, if it turns off please make sure you are connected to the correct Wi-Fi and reload the page.\"\n"
"\n"
"            const response = await fetch('/configure', {\n"
"                method: 'POST',\n"
"                headers: { 'Content-Type': 'application/json' },\n"
"                body: JSON.stringify({ ssid: selectedNetwork.ssid, password, authMode: selectedNetwork.authMode })\n"
"            })\n"
"\n"
"            if (!response.ok) {\n"
"                document.getElementById('status').innerText = \"Failed to submit credentials.\"\n"
"            }\n"
"        }\n"
"    </script>\n"
"</body>\n"
"\n"
"</html>\n";

#endif // FSDATA_H