// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// ws2812 //
// ------ //

#define ws2812_wrap_target 0
#define ws2812_wrap 6
#define ws2812_pio_version 0

static const uint16_t ws2812_program_instructions[] = {
            //     .wrap_target
    0x7421, //  0: out    x, 1            side 0 [4] 
    0x1d24, //  1: jmp    !x, 4           side 1 [5] 
    0xb542, //  2: nop                    side 0 [5] 
    0x0000, //  3: jmp    0                          
    0xb642, //  4: nop                    side 0 [6] 
    0xb342, //  5: nop                    side 0 [3] 
    0x0000, //  6: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ws2812_program = {
    .instructions = ws2812_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = ws2812_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ws2812_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ws2812_wrap_target, offset + ws2812_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

